update scripts bash -> sh

diff --git a/scripts/.local/bin/backup b/scripts/.local/bin/backup
--- a/scripts/.local/bin/backup
+++ b/scripts/.local/bin/backup
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # Backup utility that uses parallel compression utilities whenever possible
 
 # Settings
@@ -8,100 +8,95 @@ COMPRESSION_LEVEL_ZSTD="3" # 1 to 19
 PROCESSES=$(nproc)
 
 check_dependencies() {
-	declare -a dependencies=("time" "tar" \
-		"gzip" "pigz" \
-		"bzip2" "pbzip2" \
-		"zstd" \
-		"zip")
-
-	for cmd in "${dependencies[@]}"; do
-		command -v "$cmd" >/dev/null 2>&1 || {
-			echo "Error: '${cmd}' is not installed."
-			exit 1
-		}
-	done
+    dependencies="tar gzip pigz bzip2 pbzip2 zstd zip"
+    for cmd in $dependencies; do
+        if ! command -v "$cmd" >/dev/null 2>&1; then
+            echo "Error: '${cmd}' is not installed."
+            exit 1
+        fi
+    done
 }
 
 display_help() {
-	echo "Usage: $(basename "$0") [FILE] [gzip|bzip2|zstd|zip]"
-	exit 2
+    echo "Usage: $(basename "$0") [FILE] [gzip|bzip2|zstd|zip]"
+    exit 2
 }
 
 configure_backup_dir() {
-	if [ ! -e "$BACKUP_DIR" ]; then
-		mkdir "${BACKUP_DIR}"
-	fi
+    if [ ! -e "$BACKUP_DIR" ]; then
+        mkdir "${BACKUP_DIR}"
+    fi
 }
 
 backup() {
-	if [ "$#" -ne 2 ]; then
-		display_help
-	fi
+    if [ "$#" -ne 2 ]; then
+        display_help
+    fi
 
-	input=$(echo "$1" | sed 's/\/$//') # Remove last trailing `/`
-	compression=$2
-	timestamp=$(date +'%F-%Hh%M')
-	backup_filename="${BACKUP_DIR}/${input}_${timestamp}"
-	
-	if [ ! -e "$input" ]; then
-		echo "Error: File or directory not found: ${input}"
-		exit 1
-	fi
+    input=$(echo "$1" | sed 's/\/$//') # Remove last trailing /
+    compression=$2
+    timestamp=$(date +'%F-%Hh%M')
+    backup_filename="${BACKUP_DIR}/${input}_${timestamp}"
+    
+    if [ ! -e "$input" ]; then
+        echo "Error: File or directory not found: ${input}"
+        exit 1
+    fi
 
-	echo "Initial size: $(du -sh "${input}")"
+    echo "Initial size: $(du -sh "${input}")"
 
-	case "$compression" in
-		gzip) # Fast and compatible with most UNIX systems
-			echo "Begin compression with gzip..."
-			if [ -d "$input" ]; then
-				extension="tar.gz"
-				time tar --use-compress-program="pigz -k -p ${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
-					"${backup_filename}.${extension}" -C "$(dirname "${input}")" "$(basename "${input}")"
-			else
-				extension="gz"
-				time tar --use-compress-program="pigz -k -p ${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
-					"${backup_filename}.${extension}" "${input}"
-			fi
-			;;
-		bzip2) # Slower than gzip but better compression
-			echo "Begin compression with bzip2..."
-			if [ -d "$input" ]; then
-				extension="tar.bz2"
-				time tar --use-compress-program="pbzip2 -k -p${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
-					"${backup_filename}.${extension}" -C "$(dirname "${input}")" "$(basename "${input}")"
-			else
-				extension="bz2"
-				time tar --use-compress-program="pbzip2 -k -p${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
-					"${backup_filename}.${extension}" "${input}"
-			fi
-			;;
-		zstd) # Newer compression utility that is fast and has a good compression ratio
-			echo "Begin compression with zstd..."
-			if [ -d "$input" ]; then
-				extension="tar.zst"
-				time tar --use-compress-program="zstd -v -T${PROCESSES} -${COMPRESSION_LEVEL_ZSTD}" -cvf \
-					"${backup_filename}.${extension}" -C "$(dirname "${input}")" "$(basename "${input}")"
-			else
-				extension="zst"
-				time zstd -v -T${PROCESSES} -${COMPRESSION_LEVEL_ZSTD} -o "${backup_filename}.${extension}" "${input}"
-			fi
-			;;
-		zip) # Slow but has compatibility with many systems
-			echo "Begin compression with zip..."
-			extension="zip"
-			time zip -rv -${COMPRESSION_LEVEL} "${backup_filename}.${extension}" "${input}"
-			;;
-		*)
-			echo "Error: Invalid compression option."
-			display_help
-			;;
-	esac
-	
-	echo "Backup created: $(du -h "${backup_filename}.${extension}")"
-	exit 0
+    case "$compression" in
+        gzip)
+            echo "Begin compression with gzip..."
+            if [ -d "$input" ]; then
+                extension="tar.gz"
+                tar --use-compress-program="pigz -k -p ${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
+                    "${backup_filename}.${extension}" -C "$(dirname "${input}")" "$(basename "${input}")"
+            else
+                extension="gz"
+                tar --use-compress-program="pigz -k -p ${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
+                    "${backup_filename}.${extension}" "${input}"
+            fi
+            ;;
+        bzip2)
+            echo "Begin compression with bzip2..."
+            if [ -d "$input" ]; then
+                extension="tar.bz2"
+                tar --use-compress-program="pbzip2 -k -p${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
+                    "${backup_filename}.${extension}" -C "$(dirname "${input}")" "$(basename "${input}")"
+            else
+                extension="bz2"
+                tar --use-compress-program="pbzip2 -k -p${PROCESSES} -${COMPRESSION_LEVEL}" -cvf \
+                    "${backup_filename}.${extension}" "${input}"
+            fi
+            ;;
+        zstd)
+            echo "Begin compression with zstd..."
+            if [ -d "$input" ]; then
+                extension="tar.zst"
+                tar --use-compress-program="zstd -v -T${PROCESSES} -${COMPRESSION_LEVEL_ZSTD}" -cvf \
+                    "${backup_filename}.${extension}" -C "$(dirname "${input}")" "$(basename "${input}")"
+            else
+                extension="zst"
+                zstd -v -T"${PROCESSES}" -"${COMPRESSION_LEVEL_ZSTD}" -o "${backup_filename}.${extension}" "${input}"
+            fi
+            ;;
+        zip)
+            echo "Begin compression with zip..."
+            extension="zip"
+            zip -rv -"${COMPRESSION_LEVEL}" "${backup_filename}.${extension}" "${input}"
+            ;;
+        *)
+            echo "Error: Invalid compression option."
+            display_help
+            ;;
+    esac
+    
+    echo "Backup created: $(du -h "${backup_filename}.${extension}")"
+    exit 0
 }
 
 set -e
 check_dependencies
 configure_backup_dir
-backup $1 $2
+backup "$1" "$2"
diff --git a/scripts/.local/bin/xf b/scripts/.local/bin/xf
--- a/scripts/.local/bin/xf
+++ b/scripts/.local/bin/xf
@@ -1,99 +1,99 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # e(x)tract (f)ile
 
 print_format() {
-  echo "Extracting archive format: $1"
+    echo "Extracting archive format: $1"
 }
 
 check_tool() {
-  command -v "$1" >/dev/null 2>&1 || { echo >&2 "$1 is required but it's not installed"; exit 1; }
+    command -v "$1" >/dev/null 2>&1 || { echo >&2 "$1 is required but it's not installed"; exit 1; }
 }
 
 display_help() {
-  echo "Usage: `basename $0` [FILE]"
-  exit 0
+    echo "Usage: $(basename "$0") [FILE]"
+    exit 0
 }
 
 extract() {
-  if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    display_help
-  elif [ -f "$1" ]; then
-    case "$1" in
-      *.tar|*.tar.xz|*.tar.gz|*.tgz|*.tar.bz2|*.tbz2|*.txz)
-        print_format "tar"
-        check_tool tar
-        tar xvf "$1" ;;
-      *.bz2)
-        print_format "bzip2"
-        check_tool bunzip2
-        bunzip2 -v "$1" ;;
-      *.rar)
-        print_format "rar"
-        check_tool unrar
-        unrar x "$1" ;;
-      *.7z)
-        print_format "7z"
-        check_tool 7z
-        7z x "$1" ;;
-      *.gz)
-        print_format "gzip"
-        check_tool gunzip
-        gunzip -v "$1" ;;
-      *.zip)
-        print_format "zip"
-        check_tool unzip
-        unzip "$1" ;;
-      *.lz4)
-        print_format "lz4"
-        check_tool unlz4
-        unlz4 "$1" ;;
-      *.zst)
-        print_format "zstd"
-        check_tool unzstd
-        unzstd "$1" ;;
-      *.xz)
-        print_format "xz"
-        check_tool unxz
-        unxz -v "$1" ;;
-      *.iso)
-        extracted=iso_$(date +%Y-%m-%d_%H-%M-%S)
-        print_format "iso extracted to $extracted"
-        check_tool 7z
-        7z x "$1" -o"$extracted" ;;
-      *.deb)
-        print_format "deb"
-        check_tool dpkg
-        dpkg -x "$1" . ;;
-      *.rpm)
-        print_format "rpm"
-        check_tool rpm2cpio
-        rpm2cpio "$1" | cpio -id ;;
-      *.jar)
-        print_format "jar"
-        check_tool jar
-        jar xf "$1" ;;
-      *.cab)
-        print_format "cab"
-        check_tool cabextract
-        cabextract -v "$1" ;;
-      *.arj)
-        print_format "arj"
-        check_tool arj
-        arj x "$1" ;;
-      *.cpio)
-        print_format "cpio"
-        check_tool cpio
-        cpio -id < "$1" ;;
-      *.Z)
-        print_format "Z"
-        check_tool uncompress
-        uncompress -v "$1" ;;
-      *)
-        echo "'$1' could not be extracted: unsupported file format" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
-  fi
+    if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+        display_help
+    elif [ -f "$1" ]; then
+        case "$1" in
+            *.tar|*.tar.xz|*.tar.gz|*.tgz|*.tar.bz2|*.tbz2|*.txz)
+                print_format "tar"
+                check_tool tar
+                tar xvf "$1" ;;
+            *.bz2)
+                print_format "bzip2"
+                check_tool bunzip2
+                bunzip2 -v "$1" ;;
+            *.rar)
+                print_format "rar"
+                check_tool unrar
+                unrar x "$1" ;;
+            *.7z)
+                print_format "7z"
+                check_tool 7z
+                7z x "$1" ;;
+            *.gz)
+                print_format "gzip"
+                check_tool gunzip
+                gunzip -v "$1" ;;
+            *.zip)
+                print_format "zip"
+                check_tool unzip
+                unzip "$1" ;;
+            *.lz4)
+                print_format "lz4"
+                check_tool unlz4
+                unlz4 "$1" ;;
+            *.zst)
+                print_format "zstd"
+                check_tool unzstd
+                unzstd "$1" ;;
+            *.xz)
+                print_format "xz"
+                check_tool unxz
+                unxz -v "$1" ;;
+            *.iso)
+                extracted="iso_$(date +%Y-%m-%d_%H-%M-%S)"
+                print_format "iso extracted to $extracted"
+                check_tool 7z
+                7z x "$1" -o"$extracted" ;;
+            *.deb)
+                print_format "deb"
+                check_tool dpkg
+                dpkg -x "$1" . ;;
+            *.rpm)
+                print_format "rpm"
+                check_tool rpm2cpio
+                rpm2cpio "$1" | cpio -id ;;
+            *.jar)
+                print_format "jar"
+                check_tool jar
+                jar xf "$1" ;;
+            *.cab)
+                print_format "cab"
+                check_tool cabextract
+                cabextract -v "$1" ;;
+            *.arj)
+                print_format "arj"
+                check_tool arj
+                arj x "$1" ;;
+            *.cpio)
+                print_format "cpio"
+                check_tool cpio
+                cpio -id < "$1" ;;
+            *.Z)
+                print_format "Z"
+                check_tool uncompress
+                uncompress -v "$1" ;;
+            *)
+                echo "'$1' could not be extracted: unsupported file format" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
 }
 
-extract $1
+extract "$1"
